### ISSUE TITLE
Framebuffer support

### ISSUE THREAD

**Issue by gampam2000** [nspsck/st7735s_WeAct_Studio_TFT_port#1]
Hi,

is it somehow possible to add framebuffer support? 

I used a lot of this to write text: https://github.com/peterhinch/micropython-font-to-py 
But this writer needs a display that is derived from framebuffer.

Thanks & Best regards

**Comment by nspsck** [comment]
Hi, the framebuffer is kinda already built-in. 

You can just use `text(font, s, x, y[, fg, bg])` to write text, also you can either compile the fonts within the firmware (recommended, as this saves RAM) or just use them barebone as .py file. 

If you really are into framebuffers, just pass the framebuffer as a bitmap (bytearray) (which it essentially is) to the `bitmap()` function.

**Comment by gampam2000** [comment]
Hi, i tried out some fonts, but some are not working like this, so far only the vga fonts worked.

```
from fonts import chango_64

text="Hallo"
length = len(text)

tft.text(
        chango_64,
        text,
        tft.width() // 2 - length // 2 * font.WIDTH,
        tft.height() // 2 - font.HEIGHT,
        st7789.BLACK,
        st7789.YELLOW)
```

With this big font I get this error: 
`KeyError: WIDTH`

What is the difference between these Fonts? I looked at many examples and for some fonts the text function is used and for others the bitmap function? What is a good approach to display different Font sizes for different screens? I need Big fonts like about 70-90pixels big.

**Comment by nspsck** [comment]
Hi,
 TTF and vector fonts should be supported. Please use the `write()` function instead. For more information, please read the doc in the readme.

**Comment by gampam2000** [comment]
Hi, that worked fine.
Thanks for your help & best regards.
